// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ5QwOZgva5fkDyBjIND_giul840U6xaY',
    appId: '1:841771409037:web:1d96924d523b5f281b4cc4',
    messagingSenderId: '841771409037',
    projectId: 'notpaylasimapp-6ef6c',
    authDomain: 'notpaylasimapp-6ef6c.firebaseapp.com',
    storageBucket: 'notpaylasimapp-6ef6c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZvynrk4MbTYp5tECxF0uI4WoTo_7pX4o',
    appId: '1:841771409037:android:6013771f2f2fd0471b4cc4',
    messagingSenderId: '841771409037',
    projectId: 'notpaylasimapp-6ef6c',
    storageBucket: 'notpaylasimapp-6ef6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApC3JGUDRYV5eF_2WVLtnv45D9hBL_lEk',
    appId: '1:841771409037:ios:eb85e25e7766eb7b1b4cc4',
    messagingSenderId: '841771409037',
    projectId: 'notpaylasimapp-6ef6c',
    storageBucket: 'notpaylasimapp-6ef6c.firebasestorage.app',
    iosBundleId: 'com.example.notPaylasim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ5QwOZgva5fkDyBjIND_giul840U6xaY',
    appId: '1:841771409037:web:13e380e4ec3d96131b4cc4',
    messagingSenderId: '841771409037',
    projectId: 'notpaylasimapp-6ef6c',
    authDomain: 'notpaylasimapp-6ef6c.firebaseapp.com',
    storageBucket: 'notpaylasimapp-6ef6c.firebasestorage.app',
  );
}
